### ISSUE TITLE
Failing to import games

### ISSUE THREAD

**Issue by jhallbachner** [FiercePunchStudios/HumbleKeysLibrary#7]
On attempting to sync this library now, I receive the following error message, regardless of the status of the plugin: `Failed to import Humble Keys Library. Object reference not set to an instance of an object.`

I've verified logging in fresh to the Humble Store to see if that helped, no dice.

**Comment by devmckeon** [comment]
I have this same error. The add-on has yet to sync any keys. I have tried multiple ways to login, and attempted syncs always resolve to the same error. Happy to help troubleshoot.

**Comment by Dasmius007** [comment]
@devmckeon This issue was opened quite a while ago before I maintained the add-on, but I had a similar issue reported last year which I added more debug logging to try and diagnose. I appreciate your offer to help troubleshoot.

Please make sure you are using the latest version of Humble Keys, as well as the latest version of Playnite. Before you try to update the library, press F4 to open Settings, and click the "For developers" menu on the left. Check the "Log trace messages" checkbox to enable more detailed logging, and click Save. Now try to update the library, and attach your extensions.log file here.

You can find it by clicking Menu | About, then click "User data directory".

**Comment by devmckeon** [comment]
It does seem to be logging in and getting keys, I'm seeing them in the cached data, and many in playnite now (I just wasn't looking for enough of them, I was searching for 10 specific games I know are there, but a more thorough search shows many are indeed making it into the library before the error halts the task). 

Here's the error in log file:
```
17-07 08:59:12.457|TRACE|HumbleKeysLibrary#HumbleKeysLibrary:ProcessOrders: DB update complete
17-07 08:59:12.478|ERROR|HumbleKeysLibrary#HumbleKeysLibrary:Humble Keys Library: error System.NullReferenceException: Object reference not set to an instance of an object.
   at HumbleKeys.HumbleKeysLibrary.UpdateStoreLinks(ObservableCollection`1 links, Tpk tpkd, Boolean useDispatcher) in D:\a\HumbleKeysLibrary\HumbleKeysLibrary\HumbleKeysLibrary.cs:line 376
   at HumbleKeys.HumbleKeysLibrary.ImportNewGame(Tpk tpkd, Tag groupTag) in D:\a\HumbleKeysLibrary\HumbleKeysLibrary\HumbleKeysLibrary.cs:line 445
   at HumbleKeys.HumbleKeysLibrary.ProcessOrders(Dictionary`2 orders, IEnumerable`1 tpkds, List`1& importedGames, List`1& removedGames) in D:\a\HumbleKeysLibrary\HumbleKeysLibrary\HumbleKeysLibrary.cs:line 246
   at HumbleKeys.HumbleKeysLibrary.ImportGames(LibraryImportGamesArgs args) in D:\a\HumbleKeysLibrary\HumbleKeysLibrary\HumbleKeysLibrary.cs:line 79
17-07 08:59:12.478|TRACE|HumbleKeysLibrary#HumbleKeysLibrary:ImportGames: Imported 0 games, Removed 0 games
```

And looking at line 376 as well as the cached data it seems it's probably this entry:
```
"flowersanddeities": {
      "title": "Flowers and Deities",
      "tpkds": [
        {
          "machine_name": "flowersanddeities_choice_steam",
          "gamekey": "#####",
          "key_type": "steam",
          "visible": true,
          "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
          "key_type_human_name": "Steam",
          "class": "steambutton",
          "is_expired": false,
          "is_virtual": false
        }
      ]
    },
```

As there is no "human_name" key... and so my guess is because of `humanName.Replace(...)` after the `humanName = tpkd.human_name;`

```
                humanName = tpkd.human_name;
                steamGameLink = new Link("Steam", string.Format(steamSearchUrlMask, humanName.Replace(" ", "%2B")));
```

**Comment by Dasmius007** [comment]
@devmckeon Wow - thanks, that's great you reviewed the log, looked at our source code and found the line where it fails!

I tested your guess, and I agree that it most likely is failing because "human_name" key is null internally, since it is missing from the JSON record. I believe this issue only occurs with Humble Choice games, and since I don't have Choice myself and didn't implement the Choice features, it's a bit hard for me to fully debug.

One concern I'd have in fixing this is that there can probably be more than one record in the tpkds array, and each of them would probably be missing the same key. There is no human readable name that could be used other than the "title" key at the top of the record, but I don't know if every entry in the tpkds array could just use this same "title" (unless tpkds always contains only 1 entry). But as this function is only using it to construct a Steam Search link for the game title (since the tpkd entry is also missing "steam_app_id"), it might be able to just use the same "title" from the top of the record for each entry in the tpkds array.

Since @ecenshu implemented Choice support, I am going to assign this issue to him. We need to either add the "human_name" key to the record and assign a title to it, or otherwise pass the value to the UpdateStoreLinks() function somehow. Alternatively, we could just not add a Steam link if "human_name" is null.

**Comment by ecenshu** [comment]
Fix in PR #53
